version: '3.3'

services:
  php:
    build: .
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./:/var/www/html
    links:
    - db

  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
    - /var/lib/mysql
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    links:
      - db
    restart: always
    ports:
    - 8080:80
    environment:
    - PMA_ARBITRARY=1